-- CreateTable
CREATE TABLE `BDAY_CUST` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `CUST_NM` VARCHAR(256) NOT NULL,
    `CUST_ALT_NM` VARCHAR(88) NULL,
    `CUST_ID` VARCHAR(20) NOT NULL,
    `TELECOM` VARCHAR(2) NULL,
    `MOBILE_NO` VARCHAR(256) NOT NULL,
    `MOBILE_NO_HASH` VARCHAR(256) NOT NULL,
    `EMAIL` VARCHAR(256) NOT NULL,
    `EMAIL_HASH` VARCHAR(256) NOT NULL,
    `BIRTH_DD` DATE NOT NULL,
    `GNDR` CHAR(1) NOT NULL,
    `FOREIGNER` BIT(1) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
